gemfile: set minimum jekyll version to 3.9.4
There is a bug by the introduction of new logger that brakes
build with jekyll < 3.9.3 [0], set minimum version of
github-pages to make sure we use a version jekyll that contains
the fix:

>> bundle exec jekyll build
jekyll 3.9.2 | Error:  undefined method `[]' for nil
/usr/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
from .local/lib/ruby/3.3.0/gems/jekyll-3.9.2/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
from .local/lib/ruby/3.3.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:27:in `process'
from .local/lib/ruby/3.3.0/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
from .local/lib/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
from .local/lib/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
from .local/lib/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
from .local/lib/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
from .local/lib/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
from .local/lib/ruby/3.3.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
from .local/lib/ruby/3.3.0/bin/jekyll:25:in `load'
from .local/lib/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
from .local/lib/ruby/3.3.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
from /usr/bin/bundle:25:in `load'
from /usr/bin/bundle:25:in `<main>'

[0]: https://github.com/jekyll/jekyll/pull/9392

Signed-off-by: Rui Miguel Silva <rui.silva@linaro.org>